=== FiloSottile/Griffith/data/export_templates/template.dtd
<?xml version="1.0"?>
<!ELEMENT template (name, author, email, version, extension, description*, styles?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT styles (name+, style+)>
<!ELEMENT style (name, file, preview?)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT preview (#PCDATA)>
<!ATTLIST name xml:lang NMTOKEN #IMPLIED>
<!ATTLIST description xml:lang NMTOKEN #IMPLIED>

=== FiloSottile/Griffith/data/export_templates/html_tables/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template SYSTEM "../template.dtd">
<template>
	<name>HTML Tables</name>
	<name xml:lang="pl">Tabele HTML</name>
	<author>Piotr Ozarowski</author>
	<email>ozarow@gmail.com</email>
	<version>1.1</version>
	<extension>htm</extension>
	<description>Generates HTML with multiple tables:
each movie gets its own table
	</description>
	<description xml:lang="pl">Generuje HTML z wieloma tabelami:
kazdy film w oddzielnej tabeli
	</description>
	<styles>
		<name>Cascade Style Sheet</name>
		<name xml:lang="pl">Styl kaskadowy</name>
		<style>
			<name>Gray</name>
			<name xml:lang="pl">Szary</name>
			<file>gray.css</file>
			<preview>gray.jpg</preview>
		</style>
		<style>
			<name>Blue</name>
			<name xml:lang="pl">Niebieski</name>
			<file>blue.css</file>
			<preview>blue.jpg</preview>
		</style>
		<style>
			<name>Green</name>
			<name xml:lang="pl">Zielony</name>
			<file>green.css</file>
			<preview>green.jpg</preview>
		</style>
	</styles>
</template>

=== FiloSottile/Griffith/export_templates/latex/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template SYSTEM "../template.dtd">
<template>
	<name>LaTeX</name>
	<author>Piotr Ozarowski</author>
	<email>ozarow@gmail.com</email>
	<version>0.1-alpha</version>
	<extension>tex</extension>
	<description>Generates LaTeX source file</description>
	<description xml:lang="pl">Generuje plik zrodlowy LaTeXa</description>
</template>

=== FiloSottile/Griffith/data/export_templates/html_table/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template SYSTEM "../template.dtd">
<template>
	<name>HTML Table</name>
	<name xml:lang="pl">Tabela HTML</name>
	<author>Piotr Ozarowski</author>
	<email>ozarow@gmail.com</email>
	<version>1.1</version>
	<extension>htm</extension>
	<description>Generates HTML with one table</description>
	<description xml:lang="pl">Generuje HTML z jedna tabela</description>
	<styles>
		<name>Cascade Style Sheet</name>
		<name xml:lang="pl">Styl kaskadowy</name>
		<style>
			<name>Gray</name>
			<name xml:lang="pl">Szary</name>
			<file>gray.css</file>
			<preview>gray.jpg</preview>
		</style>
		<style>
			<name>Blue</name>
			<name xml:lang="pl">Niebieski</name>
			<file>blue.css</file>
			<preview>blue.jpg</preview>
		</style>
	</styles>
</template>

=== FiloSottile/Griffith/data/export_templates/csv/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template SYSTEM "../template.dtd">
<template>
	<name>CSV</name>
	<author>Piotr Ozarowski</author>
	<email>ozarow@gmail.com</email>
	<version>0.1-beta</version>
	<extension>csv</extension>
	<description>Generates simple CSV document</description>
	<description xml:lang="pl">Generuje prosty dokument CSV</description>
</template>

=== FiloSottile/Griffith/data/export_templates/xml/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE template SYSTEM "../template.dtd">
<template>
	<name>XML</name>
	<author>Piotr Ozarowski</author>
	<email>ozarow@gmail.com</email>
	<version>0.1</version>
	<extension>xml</extension>
	<description>Generates simple XML document</description>
	<description xml:lang="pl">Generuje prosty dokument XML</description>
</template>
